##################################################################################
#
#   Conformance Pack:
#     Deloitte Custom Conformance Pack
#
##################################################################################
Resources:
  Ec2SecurityGroupAttachedToEniPeriodic:
    Properties:
      ConfigRuleName: ec2-security-group-attached-to-eni-periodic
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::SecurityGroup
      Source:
        Owner: AWS
        SourceIdentifier: EC2_SECURITY_GROUP_ATTACHED_TO_ENI_PERIODIC
    Type: AWS::Config::ConfigRule
  IamGroupHasUsersCheck:
    Properties:
      ConfigRuleName: iam-group-has-users-check
      Scope:
        ComplianceResourceTypes:
        - AWS::IAM::Group
      Source:
        Owner: AWS
        SourceIdentifier: IAM_GROUP_HAS_USERS_CHECK
    Type: AWS::Config::ConfigRule
  VpcNetworkAclUnusedCheck:
    Properties:
      ConfigRuleName: vpc-network-acl-unused-check
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::NetworkAcl
      Source:
        Owner: AWS
        SourceIdentifier: VPC_NETWORK_ACL_UNUSED_CHECK
    Type: AWS::Config::ConfigRule
  WafRegionalRuleNotEmpty:
    Properties:
      ConfigRuleName: waf-regional-rule-not-empty
      Scope:
        ComplianceResourceTypes:
        - AWS::WAFRegional::Rule
      Source:
        Owner: AWS
        SourceIdentifier: WAF_REGIONAL_RULE_NOT_EMPTY
    Type: AWS::Config::ConfigRule
  CloudtrailS3DataeventsEnabled:
    Properties:
      ConfigRuleName: cloudtrail-s3-dataevents-enabled
      Source:
        Owner: AWS
        SourceIdentifier: CLOUDTRAIL_S3_DATAEVENTS_ENABLED
    Type: AWS::Config::ConfigRule
  AuditLogPolicyExists:
    Properties:
      ConfigRuleName: audit-log-policy-exists
      Description: Establish and maintain an audit log management policy that defines your organization's logging requirements. This includes, but is not limited to, review and retention of audit logs.
      Source:
        Owner: AWS
        SourceIdentifier: AWS_CONFIG_PROCESS_CHECK
    Type: AWS::Config::ConfigRule
  